name: Docker Image CI

on:
  push:
    branches: [ "8","11","17" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Docker Login
      uses: docker/login-action@v2.1.0
      with:
        username: mayan31370
        password: ${{ secrets.DOCKER_HUB_PASSWORD }}
    - name: test
      run: echo ${{ github.ref_name }}
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag mayan31370/docker-image-openj9-jvm:${{ github.ref_name }}
    - name: Push the Docker image
      run: docker push mayan31370/docker-image-openj9-jvm:${{ github.ref_name }}
